-- Juicer formal spec (Lean 4). See `garden/.../note-propeller-impl.md`.
import JuicerLean.Spec.State
import JuicerLean.Spec.Invariants
import JuicerLean.Spec.Floor
import JuicerLean.Spec.Ops
import JuicerLean.Spec.Preservation
import JuicerLean.Spec.Redemption
import JuicerLean.Spec.SubLoop
import JuicerLean.Spec.SubLoopShares
import JuicerLean.Spec.RedeemCredit
import JuicerLean.Spec.Aggregate
import JuicerLean.Spec.YieldShares
import JuicerLean.Spec.Allocation
import JuicerLean.Spec.Examples
import JuicerLean.FixedPoint.Uint256
import JuicerLean.FixedPoint.Refine
import JuicerLean.FixedPoint.Runtime
import JuicerLean.FixedPoint.Rounding
import JuicerLean.FixedPoint.YieldTransitions
import JuicerLean.FixedPoint.LazyOwnership
import JuicerLean.FixedPoint.LazyRefinement
import JuicerLean.FixedPoint.MainDebt
import JuicerLean.FixedPoint.PolicyQueue
import JuicerLean.FixedPoint.Environment
import JuicerLean.FixedPoint.Lifecycle
import JuicerLean.FixedPoint.LifecycleRefinement
import JuicerLean.FixedPoint.Orchestration
import JuicerLean.FixedPoint.MainHistories
import JuicerLean.FixedPoint.QueueHistories
import JuicerLean.FixedPoint.Checked
import JuicerLean.FixedPoint.CheckedRefinement
